import { SelectChoice } from '../../types/selectChoice.type';

export const subTypes: SelectChoice[] = [
  { value: 'CONSUMABLE', label: 'Consumable' },
  { value: 'POTION', label: 'Potion' },
  { value: 'ELIXIR', label: 'Elixir' },
  { value: 'FLASK', label: 'Flask' },
  { value: 'SCROLL', label: 'Scroll' },
  { value: 'FOOD_DRINK', label: 'Food/Drink' },
  { value: 'ITEM_ENHANCEMENT', label: 'Item Enhancement' },
  { value: 'BANDAGE', label: 'Bandage' },
  { value: 'OTHER', label: 'Other' },
  { value: 'BAG', label: 'Bag' },
  { value: 'SOUL_BAG', label: 'Soul Bag' },
  { value: 'HERB_BAG', label: 'Herb Bag' },
  { value: 'ENCHANTING_BAG', label: 'Enchanting Bag' },
  { value: 'ENGINEERING_BAG', label: 'Engineering Bag' },
  { value: 'GEM_BAG', label: 'Gem Bag' },
  { value: 'MINING_BAG', label: 'Mining Bag' },
  { value: 'LEATHERWORKING_BAG', label: 'Leatherworking Bag' },
  { value: 'INSCRIPTION_BAG', label: 'Inscription Bag' },
  { value: 'AXE_1H', label: 'Axe 1H' },
  { value: 'AXE_2H', label: 'Axe 2H' },
  { value: 'BOW', label: 'Bow' },
  { value: 'GUN', label: 'Gun' },
  { value: 'MACE_1H', label: 'Mace 1H' },
  { value: 'MACE_2H', label: 'Mace 2H' },
  { value: 'POLEARM', label: 'Polearm' },
  { value: 'SWORD_1H', label: 'Sword 1H' },
  { value: 'SWORD_2H', label: 'Sword 2H' },
  { value: 'OBSOLETE', label: 'Obsolete' },
  { value: 'STAFF', label: 'Staff' },
  { value: 'EXOTIC', label: 'Exotic' },
  { value: 'EXOTIC_2', label: 'Exotic 2' },
  { value: 'FIST_WEAPON', label: 'Fist Weapon' },
  { value: 'MISC_WEAPON', label: 'Misc Weapon' },
  { value: 'DAGGER', label: 'Dagger' },
  { value: 'THROWN', label: 'Thrown' },
  { value: 'SPEAR', label: 'Spear' },
  { value: 'CROSSBOW', label: 'Crossbow' },
  { value: 'WAND', label: 'Wand' },
  { value: 'FISHING_POLE', label: 'Fishing Pole' },
  { value: 'RED_GEM', label: 'Red Gem' },
  { value: 'BLUE_GEM', label: 'Blue Gem' },
  { value: 'YELLOW_GEM', label: 'Yellow Gem' },
  { value: 'PURPLE_GEM', label: 'Purple Gem' },
  { value: 'GREEN_GEM', label: 'Green Gem' },
  { value: 'ORANGE_GEM', label: 'Orange Gem' },
  { value: 'META_GEM', label: 'Meta Gem' },
  { value: 'SIMPLE_GEM', label: 'Simple Gem' },
  { value: 'PRISMATIC_GEM', label: 'Prismatic Gem' },
  { value: 'MISC', label: 'Misc' },
  { value: 'CLOTH_EQUIP', label: 'Cloth Equip' },
  { value: 'LEATHER_EQUIP', label: 'Leather Equip' },
  { value: 'MAIL_EQUIP', label: 'Mail Equip' },
  { value: 'PLATE_EQUIP', label: 'Plate Equip' },
  { value: 'BUCKLER_OBSOLETE', label: 'Buckler Obsolete' },
  { value: 'SHIELD_EQUIP', label: 'Shield Equip' },
  { value: 'IDOL_EQUIP', label: 'Idol Equip' },
  { value: 'TOTEM_EQUIP', label: 'Totem Equip' },
  { value: 'SIGIL_EQUIP', label: 'Sigil Equip' },
  { value: 'REAGENT', label: 'Reagent' },
  { value: 'ARROW_EQUIP', label: 'Arrow Equip' },
  { value: 'BULLET_EQUIP', label: 'Bullet Equip' },
  { value: 'TRADE_GOODS', label: 'Trade Goods' },
  { value: 'TRADE_PARTS', label: 'Trade Parts' },
  { value: 'TRADE_EXPLOSIVES', label: 'Trade Explosives' },
  { value: 'TRADE_DEVICES', label: 'Trade Devices' },
  { value: 'TRADE_JEWELCRAFTING', label: 'Trade Jewelcrafting' },
  { value: 'TRADE_CLOTH', label: 'Trade Cloth' },
  { value: 'TRADE_LEATHER', label: 'Trade Leather' },
  { value: 'TRADE_METAL_STONE', label: 'Trade Metal Stone' },
  { value: 'TRADE_MEAT', label: 'Trade Meat' },
  { value: 'TRADE_HERB', label: 'Trade Herb' },
  { value: 'TRADE_ELEMENTAL', label: 'Trade Elemental' },
  { value: 'TRADE_OTHER', label: 'Trade Other' },
  { value: 'TRADE_ENCHANTING', label: 'Trade Enchanting' },
  { value: 'TRADE_MATERIALS', label: 'Trade Materials' },
  { value: 'TRADE_ARMOR_ENCHANTMENT', label: 'Trade Armor Enchantment' },
  { value: 'TRADE_WEAPON_ENCHANTMENT', label: 'Trade Weapon Enchantment' },
  { value: 'BOOK', label: 'Book' },
  { value: 'LEATHERWORKING_RECIPE', label: 'Leatherworking Recipe' },
  { value: 'TAILORING_RECIPE', label: 'Tailoring Recipe' },
  { value: 'ENGINEERING_RECIPE', label: 'Engineering Recipe' },
  { value: 'BLACKSMITHING_RECIPE', label: 'Blacksmithing Recipe' },
  { value: 'COOKING_RECIPE', label: 'Cooking Recipe' },
  { value: 'ALCHEMY_RECIPE', label: 'Alchemy Recipe' },
  { value: 'FIRST_AID_RECIPE', label: 'First Aid Recipe' },
  { value: 'ENCHANTING_RECIPE', label: 'Enchanting Recipe' },
  { value: 'FISHING_RECIPE', label: 'Fishing Recipe' },
  { value: 'JEWELCRAFTING_RECIPE', label: 'Jewelcrafting Recipe' },
  { value: 'QUIVER', label: 'Quiver' },
  { value: 'AMMO_POUCH', label: 'Ammo Pouch' },
  { value: 'QUEST', label: 'Quest' },
  { value: 'KEY', label: 'Key' },
  { value: 'LOCKPICK', label: 'Lockpick' },
  { value: 'JUNK', label: 'Junk' },
  { value: 'MISC_REAGENT', label: 'Miscellaneous Reagent' },
  { value: 'PET', label: 'Pet' },
  { value: 'HOLIDAY', label: 'Holiday' },
  { value: 'OTHER_MISC', label: 'Other Miscellaneous' },
  { value: 'MOUNT', label: 'Mount' },
  { value: 'WARRIOR', label: 'Warrior' },
  { value: 'PALADIN', label: 'Paladin' },
  { value: 'HUNTER', label: 'Hunter' },
  { value: 'ROGUE', label: 'Rogue' },
  { value: 'PRIEST', label: 'Priest' },
  { value: 'DEATH_KNIGHT', label: 'Death Knight' },
  { value: 'SHAMAN', label: 'Shaman' },
  { value: 'MAGE', label: 'Mage' },
  { value: 'WARLOCK', label: 'Warlock' },
  { value: 'DRUID', label: 'Druid' },
];

export const schoolOptions: SelectChoice[] = [
  { value: 'addArcane', label: 'Arcane' },
  { value: 'addFire', label: 'Fire' },
  { value: 'addFrost', label: 'Frost' },
  { value: 'addGet', label: 'Get' },
  { value: 'addHoly', label: 'Holy' },
  { value: 'addMod', label: 'Mod' },
  { value: 'addNature', label: 'Nature' },
  { value: 'addPhysical', label: 'Physical' },
  { value: 'addShadow', label: 'Shadow' },
];

export const materialOptions: SelectChoice[] = [
  { value: 'CHAIN', label: 'Chain' },
  { value: 'CLOTH', label: 'Cloth' },
  { value: 'CONSUMABLES', label: 'Consumables' },
  { value: 'JEWELRY', label: 'Jewelry' },
  { value: 'LEATHER', label: 'Leather' },
  { value: 'LIQUID', label: 'Liquid' },
  { value: 'METAL', label: 'Metal' },
  { value: 'PLATE', label: 'Plate' },
  { value: 'UNDEFINED', label: 'Undefined' },
  { value: 'WOOD', label: 'Wood' },
];

export const armorTypeOptions: SelectChoice[] = [
  { value: 'LEATHER', label: 'Leather' },
  { value: 'MAIL', label: 'Mail' },
  { value: 'CLOTH', label: 'Cloth' },
  { value: 'PLATE', label: 'Plate' },
  { value: 'SHIELD', label: 'Shield' },
];

export const slotOptions: SelectChoice[] = [
  { value: 'CHEST', label: 'Chest' },
  { value: 'LEGS', label: 'Legs' },
  { value: 'HEAD', label: 'Head' },
  { value: 'SHOULDER', label: 'Shoulder' },
  { value: 'FEET', label: 'Feet' },
  { value: 'HANDS', label: 'Hands' },
  { value: 'WAIST', label: 'Waist' },
  { value: 'WRISTS', label: 'Wrist' },
  { value: 'SHIRT', label: 'Shirt' },
];
